#:schema https://raw.githubusercontent.com/razterizer/forge/main/schemas/forge.recipe.schema.json

[project]
name = "Christmas_Demo"
version = "1.3.0"
type = "executable"
cpp_std = 20

[sources]
paths = ["Christmas_Demo/christmas_demo.cpp"]

[build]
number = 6

[defaults]
style = "github-package"
profile = "applaudio"

[runtime]
files = [{ source = "Christmas_Demo/deck_the_halls.ct", destination = "deck_the_halls.ct" }, { source = "Christmas_Demo/jingle_bells.ct", destination = "jingle_bells.ct" }, { source = "Christmas_Demo/nigh_bethlehem.ct", destination = "nigh_bethlehem.ct" }, { source = "Christmas_Demo/silent_night.ct", destination = "silent_night.ct" }]

[release]
build_number_format = "dotted"

[dependencies.style.local-source]
8Beat = { path = "../lib/8Beat" }
Core = { path = "../lib/Core" }
Termin8or = { path = "../lib/Termin8or" }

[dependencies.style.git-source]
8Beat = { git = "https://github.com/razterizer/8Beat.git", commit = "27b9de666e5d583acc9a2c73085f504b7afbaa72" }
Core = { git = "https://github.com/razterizer/Core.git", commit = "3f9f712457427fddd5eb7c47960a4d7399477598" }
Termin8or = { git = "https://github.com/razterizer/Termin8or.git", commit = "d741a3dcaaeca9241ff394c38c068aa7cfddc6b6" }

[dependencies.style.github-package]
Termin8or = { github = "razterizer/Termin8or", version = "3.0.3+build.9" }

[dependencies.style.github-package.profile.applaudio]
8Beat = { github = "razterizer/8Beat", version = "1.0.3+build.6", variant = "applaudio" }

[profile.workflow-release.dependencies]
8Beat = { github = "razterizer/8Beat", version = "1.0.3+build.6", variant = "applaudio" }
Termin8or = { github = "razterizer/Termin8or", version = "3.0.3+build.9" }

[profile.workflow-release.build]
configuration = "Release"
defines = ["USE_APPLAUDIO"]

[build.config.debug]
configuration = "Debug"
defines = ["DEBUG=1"]

[build.config.release]
configuration = "Release"

[build.profile.applaudio]
defines = ["USE_APPLAUDIO"]
