format = 2

[[dependency]]
name = "8Beat"
github = "razterizer/8Beat"
package = "8Beat"
variant = "applaudio"
version = "1.0.5+build.8"
target = "any"
url = "https://github.com/razterizer/8Beat/releases/download/release-1.0.5.8/8Beat-1.0.5+build.8-applaudio-ho.cbox"
sha256 = "cbc38d4abe6577db3823eb377924fcd8f0da8a2d0817ea51f25696eb35f9040a"

[[dependency]]
name = "Core"
github = "razterizer/Core"
package = "Core"
version = "1.5.1+build.9"
target = "any"
url = "https://github.com/razterizer/Core/releases/download/release-1.5.1.9/Core-1.5.1+build.9-ho.cbox"
sha256 = "10952ce69e75e265931a858931ef610f1a810853f11e3f3405a0d526545ba870"

[[dependency]]
name = "Termin8or"
github = "razterizer/Termin8or"
package = "Termin8or"
version = "3.0.4+build.10"
target = "any"
url = "https://github.com/razterizer/Termin8or/releases/download/release-3.0.4.10/Termin8or-3.0.4+build.10-ho.cbox"
sha256 = "42708be81446750132e72e38b599f63ada9a052ddd57a122fd642300ac2610f0"
